### ISSUE TITLE
What framework do we use

### ISSUE THREAD

**Issue by xiaoxiao921** [risk-of-thunder/BepInEx.GUI#2]
I saw MAUI but it still require VS preview version right now and also I realized that its still XAML...
We would like cross platforms, right, so... is it web framework time ?!

**Comment by harbingerofme** [comment]
I was thinking http://avaloniaui.net/

**Comment by PassivePicasso** [comment]
Avalonia is well established and cross platform, its also XAML.
MAUI isn't ready overall, Avalonia is a better choice.
Going cross platform using a web framework means embedding a browser engine in a simple UI presenter, if that choice is because you want to avoid XAML, that's not a good enough reason to cost users some 150mbs of ram for ease of development.
